src/telegram_bots/apps/top_charts/urls.py
from django.urls import path
from django.views.decorators.cache import cache_page
from django.views.decorators.csrf import csrf_exempt
from telegram_bots.apps.top_charts.views import (
    all_time_music_video_chart_view,
    PeriodicMonthlyChartTaskView,
    PeriodicWeeklyChartTaskView,
    trailers_chart_view,
    ww_music_video_chart_view,
    ww_ua_and_ru_video_chart_view,
)

# from telegram_bots.apps.top_charts.views import (
#     ATMusicVideoChartView,
#     RUMusicVideoChartView,
#     TrailersChartView,
#     WWMusicVideoChartView,
# )

app_name = "top-charts"

urlpatterns = [
    # path("", cache_page(60)(WWMusicVideoChartView.as_view()), name="index"),
    path("", cache_page(60)(ww_music_video_chart_view), name="index"),
    path(
        "top-ru-music-videos/",
        cache_page(60)(ww_ua_and_ru_video_chart_view),
        name="top-ru-music-videos",
    ),
    # path(
    #     "top-all-time-music-videos/",
    #     cache_page(60)(ATMusicVideoChartView.as_view()),
    #     name="top-all-time-music-videos",
    # ),
    path(
        "top-all-time-music-videos/",
        cache_page(60)(all_time_music_video_chart_view),
        name="top-all-time-music-videos",
    ),
    # path(
    #     "top-movie-trailers/",
    #     cache_page(60)(TrailersChartView.as_view()),
    #     name="top-movie-trailers",
    # ),
    path(
        "top-movie-trailers/",
        cache_page(60)(trailers_chart_view),
        name="top-movie-trailers",
    ),
    path(
        "periodic-task/",
        csrf_exempt(PeriodicMonthlyChartTaskView.as_view()),
        name="periodic-monthly-task",
    ),
    path(
        "periodic-weekly-task/",
        csrf_exempt(PeriodicWeeklyChartTaskView.as_view()),
        name="periodic-weekly-task",
    ),
]

src/telegram_bots/urls.py
from django.contrib import admin
from django.contrib.sitemaps.views import sitemap
from django.urls import include, path
from django.views.decorators.cache import cache_page
from django.views.decorators.csrf import csrf_exempt
from django.views.generic import TemplateView
from telegram_bots.apps.teams_organizer.views import TeamsOrganizerView
from telegram_bots.apps.top_charts import urls as top_chart_urls
from telegram_bots.apps.top_charts.views import TopChartBotView
from telegram_bots.sitemaps import DynamicViewSitemap, StaticViewSitemap
from telegram_bots.views import AboutView, offline

sitemaps = {"static": StaticViewSitemap, "dynamic": DynamicViewSitemap}

urlpatterns = [
    path("admin/", admin.site.urls),
    path(
        "webhook/team/team_organizer_bot_007/",
        csrf_exempt(TeamsOrganizerView.as_view()),
    ),
    path(
        "webhook/charts/top_chart_bot_007/",
        csrf_exempt(TopChartBotView.as_view()),
    ),
    path(
        "sitemap.xml",
        sitemap,
        {"sitemaps": sitemaps},
        name="django.contrib.sitemaps.views.sitemap",
    ),
    path(
        "sw.js",
        TemplateView.as_view(template_name="sw.js", content_type="application/javascript"),
        name="sw.js",
    ),
    path("about/", cache_page(5)(AboutView.as_view()), name="about"),
    path("offline/", offline, name="offline"),
    path("", include(top_chart_urls, namespace="charts")),
]

src/telegram_bots/apps/teams_organizer/models.py
from django.db import models


class TeamOrganizerCollection(models.Model):
    """Team Organizer ORM."""

    chat_id = models.CharField(max_length=150, blank=False, null=False, unique=True, db_index=True)

    price = models.FloatField(default=0)
    participants = models.BinaryField()
    limit = models.SmallIntegerField(blank=False, null=False, default=15)
    language_code = models.CharField(default="en", max_length=5)

    class Meta:
        verbose_name = "Team Organizer Collection"
        verbose_name_plural = "Team Organizer Collections"

src/telegram_bots/apps/top_charts/models.py
import datetime as dt

from django.db import models


class YouTubeChart(models.Model):
    """YouTube Chart model."""

    name = models.CharField(max_length=50, blank=False)
    date = models.DateField(db_index=True)
    processed = models.BooleanField(default=False)

    WORLDWIDE = "WW"
    RU = "RU"
    ALL_TIME = "AT"
    TRAILER = "TR"
    CHART_TYPE_CHOICES = [
        (WORLDWIDE, "Worldwide"),
        (RU, "RU"),
        (ALL_TIME, "All time"),
        (TRAILER, "Trailers"),
    ]
    chart_type = models.CharField(
        max_length=2,
        choices=CHART_TYPE_CHOICES,
        default=WORLDWIDE,
        db_index=True,
    )

    class Meta:
        """Meta class."""

        verbose_name = "YouTube Chart"
        verbose_name_plural = "YouTube Charts"
        unique_together = (("date", "chart_type"),)


class YouTubeVideo(models.Model):
    """YouTube Vido model."""

    chart = models.ForeignKey(YouTubeChart, on_delete=models.CASCADE, related_name="videos")

    published_at = models.DateField(default=dt.datetime.today, blank=False, null=False)
    position = models.PositiveIntegerField()
    video_id = models.CharField(max_length=50, blank=False, null=False)
    title = models.CharField(max_length=150, blank=False, null=False)
    url = models.URLField(blank=False, null=False)
    vpd = models.BigIntegerField(blank=False, null=False)
    vpd_str = models.CharField(max_length=10, default="1k", blank=False, null=False)
    rank = models.BigIntegerField(blank=False, null=False, default=1)
    rank_str = models.CharField(max_length=10, default="1k", blank=False, null=False)
    views_str = models.CharField(max_length=50, blank=False, null=False)
    likes_str = models.CharField(max_length=50, blank=False, null=False)
    dislikes_str = models.CharField(max_length=50, blank=False, null=False)
    views_num = models.BigIntegerField(blank=False, null=False)
    likes_num = models.BigIntegerField(blank=False, null=False)
    dislikes_num = models.BigIntegerField(blank=False, null=False)

    class Meta:
        """Meta class."""

        verbose_name = "YouTube Video"
        verbose_name_plural = "YouTube Videos"


class TopChartTelegramChats(models.Model):
    """Telegram chat model for Top Charts."""

    chat_id = models.CharField(max_length=150, blank=False, null=False, unique=True, db_index=True)
    is_active = models.BooleanField(default=False)

    class Meta:
        """Meta class."""

        verbose_name = "TopChart Telegram Chat"
        verbose_name_plural = "TopChart Telegram Chats"


class TelegramCallbackMessage(models.Model):
    """Callback message class."""

    t_msg_id = models.CharField(max_length=150, unique=True, db_index=True)
    date_created = models.DateField()

    class Meta:
        """Meta class."""

        verbose_name = "Telegram Callback message"
        verbose_name_plural = "Telegram Callback messages"


class TelegramCallbackUserReaction(models.Model):
    """Callback user reaction class."""

    message = models.ForeignKey(
        TelegramCallbackMessage, on_delete=models.CASCADE, related_name="users"
    )

    # 0, 1, -1
    value = models.SmallIntegerField()
    user_id = models.CharField(max_length=150, db_index=True)

    class Meta:
        """Meta class."""

        verbose_name = "Telegram Callback user reaction"
        verbose_name_plural = "Telegram Callback user reactions"
        unique_together = ["message", "user_id"]

src/telegram_bots/apps/users/models.py
from django.contrib.auth.models import AbstractUser


class User(AbstractUser):
    """Custom (extended) user model.

    The user model is extended by default, in this way
    we don't have to bother with difficult migrations in the future.
    """

    USERNAME_FIELD = "username"

    def __str__(self):
        return self.get_username()


User._meta.get_field("email").blank = False

src/telegram_bots/apps/teams_organizer/views.py
import json
import logging

from django.http import JsonResponse
from django.views import View
from telegram_bots.apps.teams_organizer.bot_methods import TeamOrganizer
from telegram_bots.apps.teams_organizer.utils.helpers import help_msg, help_set_msg
from telegram_bots.utils.text import args_handler

logger = logging.getLogger("team_organizer")


# https://api.telegram.org/bot<token>/setWebhook?url=<url>/webhook/team/team_organizer_bot_007/
class TeamsOrganizerView(View):
    """Team Organizer view class."""

    def post(self, request, *args, **kwargs) -> JsonResponse:
        """Read and process the chat message."""
        try:
            t_data = json.loads(request.body)
        except Exception as e:
            logger.error(f"Error during the message convert to JSON: {e}")
            return JsonResponse({"ok": "POST request processed with errors."})

        try:
            t_message = t_data["message"]
        except KeyError as e:
            logger.error(f"Cannot read the message: {e}. Data: {t_data}")
            return JsonResponse({"ok": "POST request processed with errors."})

        try:
            t_chat = t_message["chat"]
            text = t_message["text"].strip().lower()
            text = text.lstrip("/")
            chat = TeamOrganizer(t_chat, t_message["from"])
        except Exception as e:
            logger.error(f"Can't read the chat message: {e}")
            return JsonResponse({"ok": "POST request processed with errors."})

        try:
            self.process_message(text, chat)
        except Exception as e:
            logger.error(f"Can't process the message: {e}")
            try:
                chat.send_organizer_message(str(e))
            except Exception as e:
                logger.error(f"Can't send message ot the chat: {e}")
                chat.send_organizer_message("ERROR blyat")

        return JsonResponse({"ok": "POST request processed"})

    @staticmethod
    def process_message(text: str, chat: TeamOrganizer):
        """Process chat message."""
        if text == "+":
            message_to_bot = chat.add_person()
        elif text.startswith("+"):
            message_to_bot = chat.add_guests(text)
        elif text == "-":
            message_to_bot = chat.remove_person()
        elif text.startswith("-"):
            message_to_bot = chat.remove_guests(text)
        elif text == "help" or text == "start":
            message_to_bot = help_msg()
        elif text == "help-set" or text == "start":
            message_to_bot = help_set_msg()
        elif text == "list":
            message_to_bot = chat.list_of_participants()
        elif text == "restart" or text == "reset":
            message_to_bot = chat.restart()
        elif text.startswith("set"):
            args, error = args_handler("set", text)
            if error:
                message_to_bot = error
            else:
                message_to_bot = chat.parse_set_methods(args)
        else:
            message_to_bot = chat.error_msg()

        chat.send_organizer_message(message_to_bot)

src/telegram_bots/apps/top_charts/views/bot_view.py
import json
import logging

from django.http import JsonResponse
from django.views import View
from telegram_bots.apps.top_charts.models import TopChartTelegramChats

from telegram_bots.apps.top_charts.utils import TopChartBot

__all__ = ["TopChartBotView"]


logger = logging.getLogger("top_chart_bot")


class TopChartBotView(View):
    """Top Chart Bot view."""

    def post(self, request, *args, **kwargs) -> JsonResponse:
        """Process the chart bot request."""
        data = json.loads(request.body)

        if self.is_start_channel_msg(data):
            return JsonResponse({"ok": "POST request processed"})

        if not self.is_chat_can_be_processed(data):
            return JsonResponse({"ok": "POST request processed"})

        t_message = data.get("callback_query")
        if t_message:
            top_chart_bot = TopChartBot(t_message)
            top_chart_bot.update_counter()

        return JsonResponse({"ok": "POST request processed"})

    @staticmethod
    def is_start_channel_msg(data: dict) -> bool:
        """Check if it is a first time the channel messaged."""
        t_message = data.get("channel_post")
        if not t_message:
            return False

        t_chat = t_message["chat"]
        try:
            TopChartTelegramChats.objects.get_or_create(chat_id=str(t_chat["id"]))
        except Exception as e:
            logger.error(f"Exception during the chat creation: {e}")
            return False

        return True

    @staticmethod
    def is_chat_can_be_processed(data: dict) -> bool:
        """Check if it is a first time the channel messaged."""
        t_message = data.get("callback_query", {}).get("message")
        if not t_message:
            return False

        try:
            text = t_message["text"].strip().lower()
        except KeyError:
            logger.error(f"Message doesn't contain 'text' which is required: {t_message}")
            return False

        text = text.lstrip("/")
        t_chat = t_message["chat"]

        try:
            TopChartTelegramChats.objects.get_or_create(chat_id=str(t_chat["id"]))
        except Exception as e:
            logger.error(f"Exception during the chat creation: {e}")
            return False

        return True

src/telegram_bots/views.py
from django.http import HttpResponse
from django.shortcuts import render
from django.urls import reverse
from django.utils.safestring import mark_safe
from django.views.generic.base import TemplateView


class AboutView(TemplateView):
    """Monthly chart, US region."""

    template_name = "about.html"

    def get_context_data(self, **kwargs) -> dict:
        """Get context data."""
        ctx = super().get_context_data(**kwargs)
        ctx["top_yt_video_charts"] = mark_safe(  # noqa: S308
            """
            <strong class='text-solid'> Top YouTube Video Charts </strong>
            """
        )
        ctx["yt_music_videos"] = mark_safe(  # noqa: S308
            """
            <strong class="text-solid"> YouTube Music Videos </strong>
            """
        )
        ctx["title"] = "About"
        ctx["telegram_channel"] = mark_safe(  # noqa: S308
            """
            <a href="https://t.me/dude007_channel"
               class="link-solid" rel="noreferrer" target="_blank"
               aria-label="Telegram Channel">
                Telegram Channel <i class="fab fa-telegram-plane"></i>
                <i class="fas fa-external-link-alt"></i>
            </a>
            """
        )
        ctx["weekly_top_video_chart"] = mark_safe(  # noqa: S308, S703
            """
            <strong class="text-solid">Weekly Top Video Chart</strong>.
            """
        )
        href_text = f"""href="{reverse('charts:top-all-time-music-videos')}" """  # noqa: B907
        ctx["all_time_music_videos"] = mark_safe(  # noqa: S308, S703
            f"""
            <a {href_text}
               class="link-solid">
                All Time Music Videos <i class="fas fa-link"></i>
            </a>
            """
        )
        ctx["pwa"] = mark_safe(  # noqa: S308, S703
            """
            <strong class="text-solid">
            Progressive Web Application(PWA)
            </strong>
            """
        )
        ctx["olha_linkedin"] = mark_safe(  # noqa: S308, S703
            """
            <a href="http://www.linkedin.com/in/olha-voronova/"
               class="link-solid"
               rel="noreferrer"
               target="_blank"
               aria-label="LinkedIn">
                Olha <i class="fab fa-linkedin"></i>
                <i class="fas fa-external-link-alt"></i>
            </a>
            """
        )
        href_text = f"""href="{reverse('charts:index')}" """  # noqa: B907
        ctx["yt_video_charts_link"] = mark_safe(  # noqa: S308, S703
            f"""
            <a {href_text}
               class="link-solid">
                YouTube Video Charts <i class="fas fa-link"></i>
            </a>
            """
        )
        ctx["linkedin_url"] = mark_safe(  # noqa: S308, S703
            """
            <a href="https://www.linkedin.com/in/anvoronov/?locale=en_US"
               target="_blank"
               class="link-solid">
                LinkedIn <i class="fab fa-linkedin"></i>
                <i class="fas fa-external-link-alt"></i>
            </a>
            """
        )
        ctx["instagram_url"] = mark_safe(  # noqa: S308, S703
            """
            <a href="https://www.instagram.com/voronov.a.g/"
               rel="noreferrer"
               target="_blank"
               aria-label="Instagram"
               class="link-solid">
                Instagram <i class="fab fa-instagram"></i>
                <i class="fas fa-external-link-alt"></i>
            </a>
            """
        )
        return ctx


def offline(request) -> HttpResponse:
    """Build offline page."""
    data = {
        "title": "Top Charts Offline",
        "h1": "Top Charts Offline Mode",
        "text": (
            "You are viewing web site in offline mode. "
            "Videos aren't accessible without internet connection. "
        ),
        "meta_description": ("Top chart of YouTube videos. Enjoy top videos which are InMyTop. "),
        "meta_keywords": "YouTube, videos, top chart, music, movies trailers",
    }
    return render(request, "offline.html", data)

src/telegram_bots/templates/base.html
<!DOCTYPE html>
{% load static %}
{% load i18n %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="description" content="{{ meta_description }}">
    <meta name="keywords" content="{{ meta_keywords }}">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="author" content="Andrew Voronov">
    <meta name="language" content="EN">
    <meta name="robots" content="index,follow" />

    <title>{% block title %}{{ title }}{% endblock %}</title>

    <!-- PWA -->
    <!-- Path to manifest.json -->
    <link rel="manifest" href="{% static "/manifest.json" %}">

    <!-- Add to homescreen for Chrome on Android -->
    <meta name="mobile-web-app-capable" content="yes">
    <meta name="application-name" content="Top Charts">

    <!-- Chrome for Android theme color -->
    <meta name="theme-color" content="#000321">

    <!-- Add to homescreen for Safari on iOS -->
    <meta name="apple-mobile-web-app-capable" content="yes">
    <meta name="apple-mobile-web-app-title" content="Top Charts">
    <meta name="apple-mobile-web-app-status-bar-style" content="default">

    <link rel="apple-touch-icon" href="{% static "/images/icons/icons-192.png" %}" sizes="">
    <link rel="apple-touch-icon" href="{% static "/images/icons/icons-512.png" %}" sizes="">
    <link href="{% static "/images/icons/icons-512.png" %}" rel="apple-touch-startup-image">
    <!-- iPhone Xs Max (1242px x 2688px) -->
    <link rel="apple-touch-startup-image"
          media="(device-width: 414px) and (device-height: 896px) and (-webkit-device-pixel-ratio: 3)"
          href="{% static "/images/icons/icons-512.png" %}">
    <!-- iPhone Xr (828px x 1792px) -->
    <link rel="apple-touch-startup-image"
          media="(device-width: 414px) and (device-height: 896px) and (-webkit-device-pixel-ratio: 2)"
          href="{% static "/images/icons/icons-512.png" %}">
    <!-- iPhone X, Xs (1125px x 2436px) -->
    <link rel="apple-touch-startup-image"
          media="(device-width: 375px) and (device-height: 812px) and (-webkit-device-pixel-ratio: 3)"
          href="{% static "/images/icons/icons-512.png" %}">
    <!-- iPhone 8 Plus, 7 Plus, 6s Plus, 6 Plus (1242px x 2208px) -->
    <link rel="apple-touch-startup-image"
          media="(device-width: 414px) and (device-height: 736px) and (-webkit-device-pixel-ratio: 3)"
          href="{% static "/images/icons/icons-512.png" %}">
    <!-- iPhone 8, 7, 6s, 6 (750px x 1334px) -->
    <link rel="apple-touch-startup-image"
          media="(device-width: 375px) and (device-height: 667px) and (-webkit-device-pixel-ratio: 2)"
          href="{% static "/images/icons/icons-512.png" %}">
    <!-- iPad Pro 12.9" (2048px x 2732px) -->
    <link rel="apple-touch-startup-image"
          media="(device-width: 1024px) and (device-height: 1366px) and (-webkit-device-pixel-ratio: 2)"
          href="{% static "/images/icons/icons-512.png" %}">
    <!-- iPad Pro 11” (1668px x 2388px) -->
    <link rel="apple-touch-startup-image"
          media="(device-width: 834px) and (device-height: 1194px) and (-webkit-device-pixel-ratio: 2)"
          href="{% static "/images/icons/icons-512.png" %}">
    <!-- iPad Pro 10.5" (1668px x 2224px) -->
    <link rel="apple-touch-startup-image"
          media="(device-width: 834px) and (device-height: 1112px) and (-webkit-device-pixel-ratio: 2)"
          href="{% static "/images/icons/icons-512.png" %}">
    <!-- iPad Mini, Air (1536px x 2048px) -->
    <link rel="apple-touch-startup-image"
          media="(device-width: 768px) and (device-height: 1024px) and (-webkit-device-pixel-ratio: 2)"
          href="{% static "/images/icons/icons-512.png" %}">

    <!-- Tile for Win8 -->
    <meta name="msapplication-TileColor" content="#000321">
    <meta name="msapplication-TileImage" content="{% static "/images/icons/icons-512.png" %}">

    <script type="text/javascript">
        if ('serviceWorker' in navigator) {
          window.addEventListener('load', function() {
            navigator.serviceWorker.register('/sw.js').then(function(registration) {
              // Registration was successful
              console.log('ServiceWorker registration successful with scope: ', registration.scope);
            }, function(err) {
              // registration failed :(
              console.log('ServiceWorker registration failed: ', err);
            });
          });
        }
    </script>
    <!-- *************************** -->

    <!-- Global site tag (gtag.js) - Google Analytics -->
    <script async src="https://www.googletagmanager.com/gtag/js?id=UA-27163435-8"></script>
    <script>
        window.dataLayer = window.dataLayer || [];
        function gtag(){dataLayer.push(arguments);}
        gtag('js', new Date());
        gtag('config', 'UA-27163435-8');
    </script>

    <link rel="shortcut icon" href="{% static "favicon.ico" %}" type="image/x-icon">
    <link rel="icon" href="{% static "favicon.ico" %}" type="image/x-icon">

    <!-- 3-rd party JS and CSS -->
    <script src="https://kit.fontawesome.com/a80633824a.js" crossorigin="anonymous" referrerpolicy="no-referrer"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.6.0/jquery.min.js"
        integrity="sha512-894YE6QWD5I59HgZOGReFYm4dnWc1Qt5NtvYSaNcOP+u1T9qYdvdihz0PPSiiqn/+/3e7Jo4EaG7TubfWGUrMQ=="
        crossorigin="anonymous" referrerpolicy="no-referrer"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/2.10.2/umd/popper.min.js"
            integrity="sha512-nnzkI2u2Dy6HMnzMIkh7CPd1KX445z38XIu4jG1jGw7x5tSL3VBjE44dY4ihMU1ijAQV930SPM12cCFrB18sVw=="
            crossorigin="anonymous" referrerpolicy="no-referrer"></script>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.6.1/dist/css/bootstrap.min.css"
          integrity="sha384-zCbKRCUGaJDkqS1kPbPd7TveP5iyJE0EjAuZQTgFLD2ylzuqKfdKlfG/eSrtxUkn" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.6.1/dist/js/bootstrap.min.js"
            integrity="sha384-VHvPCCyXqtD5DqJeNxl2dtTyhF78xXNXdkwX1CZeRusQfRKp+tA7hAShOK/B/fQ2"
            crossorigin="anonymous"></script>

    <!-- Local static files -->
    <link rel="stylesheet" href="{% static "css/main.css" %}">
</head>
<body>

<div class="container">
    {% url 'charts:index' as home_url %}
    {% url 'charts:top-ru-music-videos' as top_ru_videos %}
    {% url 'charts:top-all-time-music-videos' as top_at_videos %}
    {% url 'charts:top-movie-trailers' as top_trailers %}
    <nav class="navbar navbar-expand-lg navbar-dark bg-solid fixed-top">

        <a class="navbar-brand" href="/" aria-label="Top Charts Logo">
            <img src="{% static "images/icons/logo-with-text.svg" %}" alt="Top Charts" height="40px">
        </a>
        <button class="navbar-toggler" type="button" data-toggle="collapse"
                data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent"
                aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>

        <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav ml-auto">
                <li class="nav-item {% if request.path == home_url %}active{% endif %}">
                    <a class="nav-link" href="{{ home_url }}">Worldwide Music</a>
                </li>
                <li class="nav-item invisible-on-medium-down">
                    <a class="nav-link" href="#" aria-label="Separator">|</a>
                </li>
                <li class="nav-item {% if request.path == top_ru_videos %}active{% endif %}">
                    <a class="nav-link" href="{{ top_ru_videos }}">Russian Music</a>
                </li>
                <li class="nav-item invisible-on-medium-down">
                    <a class="nav-link" href="#" aria-label="Separator">|</a>
                </li>
                <li class="nav-item {% if request.path == top_at_videos %}active{% endif %}">
                    <a class="nav-link" href="{{ top_at_videos }}">All Time Music</a>
                </li>
                <li class="nav-item invisible-on-medium-down">
                    <a class="nav-link" href="#" aria-label="Separator">|</a>
                </li>
                <li class="nav-item {% if request.path == top_trailers %}active{% endif %}">
                    <a class="nav-link" href="{{ top_trailers }}">Movie Trailers</a>
                </li>
            </ul>
        </div>
    </nav>
    {% block content %}
    {% endblock %}
</div>


<nav class="navbar navbar-expand navbar-dark bg-solid">
    <div class='container'>
        <div class="collapse navbar-collapse">
            <ul class="navbar-nav w-100 nav-justified">
                <li class="nav-item active">
                    <a class="nav-link"
                       href="{% url 'about' %}"
                       rel="noreferrer"
                       aria-label="About Top Charts project">
                        <i class="far fa-2x fa-address-card"></i>
                    </a>
                </li>
                <li class="nav-item active">
                    <a class="nav-link"
                       href="https://t.me/dude007_channel"
                       rel="noreferrer"
                       target="_blank"
                       aria-label="Telegram channel dude007">
                        <i class="fab fa-2x fa-telegram-plane"></i>
                    </a>
                </li>
                <li class="nav-item active">
                    <a class="nav-link"
                       href="https://www.linkedin.com/in/anvoronov/?locale=en_US"
                       rel="noreferrer"
                       target="_blank"
                       aria-label="LinkedIn">
                        <i class="fab fa-2x fa-linkedin"></i>
                    </a>
                </li>
                <li class="nav-item">
                    <a class="nav-link active"
                       href="https://www.instagram.com/voronov.a.g/"
                       aria-label="Subscribe to my Instagram account"
                       rel="noreferrer"
                       target="_blank">
                        <i class="fab fa-2x fa-instagram"></i>
                    </a>
                </li>
            </ul>
        </div>
    </div>
</nav>


{% block additional_scripts %}
{% endblock %}
</body>
</html>

src/telegram_bots/templates/offline.html
{% extends "base.html" %}
{% load i18n %}
{% load static %}

{% block content %}
<h1 class="text-center chart-title">{{ h1 }}</h1>
    <br/>
    <br/>
<div class="row">
<div class="col-12">
    <img src="{% static "images/icons/logo-with-text.svg" %}" class="card-img-top" alt="Logo">
</div>
</div>
    <br/>
    <br/>
<div class="row">
<div class="col-12">
    <p class="text-center alert alert-danger" role="alert">{{ text }}</p>
</div>
</div>
{% endblock content %}

src/telegram_bots/templates/temp_weights.html
{% extends "base.html" %}
{% load i18n %}
{% load static %}

{% block content %}
<table class="table" style="background-color:white;margin-top:70px;">
  <thead>
    <tr>
      <th scope="col">Position New</th>
      <th scope="col">Position Old</th>
      <th scope="col">Title</th>
      <th scope="col">URL</th>
      <th scope="col">Sort Value</th>
      <th scope="col">Views</th>
      <th scope="col">VPD</th>
      <th scope="col">Likes</th>
      <th scope="col">Dislikes</th>
    </tr>
  </thead>
  <tbody>
    {% for v in videos %}
    <tr>
      <td>{{ v.new_position }}</td>
      <td>{{ v.position }}</td>
      <td>{{ v.title }}</td>
        <td><a href="{{ v.url }}">{{ v.url }}</a></td>
      <td>{{ v.sort_value }}</td>
      <td>{{ v.views_str }}</td>
      <td>{{ v.vpd_str }}</td>
      <td>{{ v.likes }}</td>
      <td>{{ v.dislikes }}</td>
    </tr>
  {% endfor %}
  </tbody>
</table>

{% endblock content %}